name: Comprehensive Tests

on:
  schedule:
    # Run comprehensive tests daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    # Allow manual triggering
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/e2e/**'
      - 'pyproject.toml'
      - 'Makefile'

jobs:
  comprehensive-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Set up Python 3.12
      run: uv python install 3.12

    - name: Install dependencies
      run: |
        uv sync --frozen --extra dev

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libxcb-cursor0 \
          libxcb-icccm4 \
          libxcb-image0 \
          libxcb-keysyms1 \
          libxcb-randr0 \
          libxcb-render-util0 \
          libxcb-xinerama0 \
          libxcb-xfixes0 \
          xvfb

    - name: Start virtual display
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        sleep 3

    - name: Run all tests with coverage
      run: |
        uv run pytest tests/ \
          --cov=src/wes \
          --cov-report=html:htmlcov \
          --cov-report=xml:coverage.xml \
          --cov-report=term-missing \
          --cov-fail-under=50 \
          --junitxml=test-results-all.xml
      env:
        DISPLAY: ":99"
        QT_QPA_PLATFORM: "offscreen"

    - name: Run end-to-end tests
      run: |
        uv run pytest tests/e2e/ \
          --junitxml=test-results-e2e.xml \
          -v
      env:
        DISPLAY: ":99"
        QT_QPA_PLATFORM: "offscreen"

    - name: Run comprehensive security scanning
      run: |
        echo "Running Bandit security scan..."
        uv run bandit -r src/ -f json -o bandit-report.json || true
        
        echo "Running Safety dependency scan..."
        uv run safety check --json --output safety-report.json || true
        
        echo "Running Semgrep security scan..."
        uv run semgrep --config=auto src/ --json --output=semgrep-report.json || true

    - name: Generate coverage report
      run: |
        uv run coverage html
        uv run coverage report --show-missing

    - name: Upload comprehensive test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: comprehensive-test-results
        path: |
          test-results-*.xml
          coverage.xml
          htmlcov/
          bandit-report.json
          safety-report.json
          semgrep-report.json

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        file: ./coverage.xml
        flags: comprehensive
        name: codecov-comprehensive
        fail_ci_if_error: false

    - name: Comment PR with test results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          
          let comment = '## 🧪 Comprehensive Test Results\n\n';
          
          // Add coverage info if available
          try {
            const coverage = fs.readFileSync('coverage.xml', 'utf8');
            const match = coverage.match(/line-rate="([^"]+)"/);
            if (match) {
              const coveragePercent = (parseFloat(match[1]) * 100).toFixed(1);
              comment += `📊 **Code Coverage:** ${coveragePercent}%\n\n`;
            }
          } catch (e) {
            console.log('Could not read coverage info');
          }
          
          // Add security scan results
          try {
            const bandit = JSON.parse(fs.readFileSync('bandit-report.json', 'utf8'));
            comment += `🔒 **Security Issues Found:** ${bandit.results.length}\n`;
          } catch (e) {
            comment += `🔒 **Security Scan:** Completed\n`;
          }
          
          try {
            const safety = JSON.parse(fs.readFileSync('safety-report.json', 'utf8'));
            comment += `🛡️ **Dependency Vulnerabilities:** ${safety.length || 0}\n`;
          } catch (e) {
            comment += `🛡️ **Dependency Scan:** Completed\n`;
          }
          
          comment += '\n✅ All comprehensive tests completed successfully!';
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });

  build-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.11", "3.12"]
    
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        uv sync --frozen
        uv add pyinstaller

    - name: Install system dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libxcb-cursor0 \
          libxcb-icccm4 \
          libxcb-image0 \
          libxcb-keysyms1 \
          libxcb-randr0 \
          libxcb-render-util0 \
          libxcb-xinerama0 \
          libxcb-xfixes0

    - name: Build executable
      run: |
        case "${{ runner.os }}" in
          "Linux")
            make build-linux
            ;;
          "Windows")
            make build-windows
            ;;
          "macOS")
            make build-macos
            ;;
        esac

    - name: Test executable
      run: |
        case "${{ runner.os }}" in
          "Linux")
            ./dist/linux/wes-linux-1.0.0 --version
            ;;
          "Windows")
            ./dist/windows/wes-windows-1.0.0.exe --version
            ;;
          "macOS")
            ./dist/macos/wes-macos-1.0.0 --version
            ;;
        esac
      env:
        QT_QPA_PLATFORM: "offscreen"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: executable-${{ matrix.os }}-py${{ matrix.python-version }}
        path: dist/
        retention-days: 30