name: Quick Checks

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop ]

jobs:
  quick-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Set up Python 3.12
      run: uv python install 3.12

    - name: Install dependencies
      run: |
        uv sync --frozen --extra dev

    - name: Check code formatting
      run: |
        uv run black --check src tests
        uv run isort --check-only src tests

    - name: Run linting (fast)
      run: |
        uv run flake8 src tests --select=E9,F63,F7,F82 --show-source --statistics

    - name: Run type checking
      run: |
        uv run mypy src/wes --fast

    - name: Run quick unit tests
      run: |
        uv run pytest tests/unit/ -x --tb=short -q
      env:
        QT_QPA_PLATFORM: "offscreen"

    - name: Check security (basic)
      run: |
        uv run bandit -r src/ --severity-level medium --confidence-level medium --quiet

    - name: Validate project structure
      run: |
        # Check that required files exist
        test -f pyproject.toml
        test -f Makefile
        test -f README.md
        test -d src/wes
        test -d tests
        
        # Check that main module is importable
        uv run python -c "import wes.main"

  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Set up Python 3.12
      run: uv python install 3.12

    - name: Install dependencies
      run: uv sync --frozen --extra dev

    - name: Run pre-commit hooks
      run: |
        uv run pre-commit run --all-files
      continue-on-error: true