name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.11", "3.12"]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        uv sync --frozen --extra dev

    - name: Install system dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libxcb-cursor0 \
          libxcb-icccm4 \
          libxcb-image0 \
          libxcb-keysyms1 \
          libxcb-randr0 \
          libxcb-render-util0 \
          libxcb-xinerama0 \
          libxcb-xfixes0 \
          xvfb

    - name: Run linting
      run: |
        uv run flake8 src tests
        uv run pylint src/wes

    - name: Run type checking
      run: |
        uv run mypy src/wes

    - name: Run unit tests
      run: |
        uv run pytest tests/unit/ \
          --cov=src/wes \
          --cov-report=xml \
          --cov-report=term-missing \
          --cov-fail-under=50 \
          --junitxml=test-results-unit.xml
      env:
        DISPLAY: ":99"
        QT_QPA_PLATFORM: "offscreen"

    - name: Run integration tests  
      run: |
        uv run pytest tests/integration/ \
          --junitxml=test-results-integration.xml
      env:
        DISPLAY: ":99"
        QT_QPA_PLATFORM: "offscreen"

    - name: Run security tests
      run: |
        uv run pytest tests/security/ \
          --junitxml=test-results-security.xml
      env:
        DISPLAY: ":99"
        QT_QPA_PLATFORM: "offscreen"

    - name: Run security scanning
      run: |
        uv run bandit -r src/ -f json -o bandit-report.json || true
        uv run safety check --json --output safety-report.json || true

    - name: Upload coverage to Codecov
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.12'
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ matrix.os }}-${{ matrix.python-version }}
        path: |
          test-results-*.xml
          bandit-report.json
          safety-report.json
          htmlcov/

  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Set up Python 3.12
      run: uv python install 3.12

    - name: Install build dependencies
      run: uv sync --frozen --extra build

    - name: Install system dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libxcb-cursor0 \
          libxcb-icccm4 \
          libxcb-image0 \
          libxcb-keysyms1 \
          libxcb-randr0 \
          libxcb-render-util0 \
          libxcb-xinerama0 \
          libxcb-xfixes0

    - name: Test Linux build
      if: runner.os == 'Linux'
      run: make build-linux

    - name: Test Windows build  
      if: runner.os == 'Windows'
      run: make build-windows

    - name: Test macOS build
      if: runner.os == 'macOS'
      run: make build-macos

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: executable-${{ matrix.os }}
        path: |
          dist/
        retention-days: 7